### ISSUE TITLE
Message acknowledgement

### ISSUE THREAD

**Issue by frabe1579** [FoundatioFx/Foundatio.RabbitMQ#1]
Hi,
Is there a method to acknowledge a received message?
With acknowledgement i can ensure a message is completely processed without errors.

**Comment by niemyjski** [comment]
We currently don't have anything to confirm the receipt of a message, would you be interested in implementing this functionality?

**Comment by totalprogrammi** [comment]
I'm thinking of changing the implementation (or creating a new one) using topic exchange instead of fanout, to allow precise routing and avoid broadcasting. I will try this next days.

**Comment by niemyjski** [comment]
Sounds good,  It might be good to add options that control the exchange behavior via our options class we pass in to the ctor?

**Comment by totalprogrammi** [comment]
I'm investigating some solutions, and the problem seems to be the different method used to route messages. For example, with Topic exchange type, you cannot use the same parameters (the same topic/routing/queue to send and receive messages, due to different behaviors of RabbitMQ routing. For this reason we have to implement different calls for different exchange types. I will start implementing a new MessageBus class using Topic exchange instead of Fanout starting from your code. In this manner we can eventually merge the different methods and use options to control the behavior.

**Comment by niemyjski** [comment]
@totalprogrammi were you able to find a good solution?

**Comment by niemyjski** [comment]
@frabe1579 were you able to find a good solution?
